### ISSUE TITLE
restify-clients not compatible with restify 5.x

### ISSUE THREAD

**Issue by retrohacker** [restify/clients#131]
`sed -i 's/restify": "^4.3.0/restify": "^5.0.0/g' package.json  && make prepush`

```

  restify-client bunyan usage tests
    ✓ no logger (48ms)
    ✓ no serializers
    ✓ bunyan stdSerializers
    ✓ some unrelated bunyan serializer "foo"
    ✓ using restify-clients exported "bunyan.serializers"

  restify-client tests
TypeError: restify.acceptParser is not a function
    at Context.<anonymous> (/home/wblankenship/Development/restify-repro/1297/node_modules/restify-clients/test/index.js:152:32)
    at callFnAsync (/home/wblankenship/Development/restify-repro/1297/node_modules/restify-clients/node_modules/mocha/lib/runnable.js:371:21)
    at Hook.Runnable.run (/home/wblankenship/Development/restify-repro/1297/node_modules/restify-clients/node_modules/mocha/lib/runnable.js:318:7)
    at next (/home/wblankenship/Development/restify-repro/1297/node_modules/restify-clients/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/home/wblankenship/Development/restify-repro/1297/node_modules/restify-clients/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Makefile:82: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by DonutEspresso** [comment]
Does this affect tests only?
