### ISSUE TITLE
Expose the server plugins/audit.js from the server to the client.

### ISSUE THREAD

**Issue by marcellodesales** [restify/clients#14]
We heavily use restify as the server with the audit on... That way, we monitor the entire Req/Res stack that comes to the server.

However, we started using the restify clients and we'd like to have the same functionality with the clients. Looking at the repository, I don't see that.

Please provide that implementation... Thanks!

**Comment by marcellodesales** [comment]
Here's what I'm looking for:

Regular Request without Auditor
------

```js
mdesales@ubuntu [10/24/2015 12:07:22] ~/dev/github-intuit/servicesplatform-nodejs/sp-http-client (develop *) $ node adapter/json.js 
{ bu: 'tech',
  site: 'SDG',
  supervisor: 'xyz',
  title: 'CEO',
  worksite: 'SDG' }
```

Request with Auditor
------

```js
~/dev/github-intuit/servicesplatform-nodejs/sp-http-client (develop *) $ node adapter/json.js 
[2015-10-24T19:53:26.732Z]  INFO: sp-http-client/JSON-HTTP-CLIENT/58611 on ubuntu (/home/mdesales/dev/github-intuit/servicesplatform-nodejs/sp-http-client/lib/auditor/index.js:40 in audit):  (appVersion=0.1.0, remoteAddress=10.137.8.28, remotePort=443, err=null, req.timers={}, req.port=443)
  GET /people/mdesales HTTP/1.1
  accept: application/json;application/xml
  authorization: IAM a=333;b=4444
  user-agent: sp-http-client/1.0.0 (x64-linux; v8/3.14.5.9; OpenSSL/1.0.1p) node/0.10.40
  accept-version: *
  date: Sat, 24 Oct 2015 19:53:26 GMT
  host: people.company.com:443
  --
  HTTP/1.1 200 OK
  date: Sat, 24 Oct 2015 19:53:26 GMT
  set-cookie: JSESSIONID=5532AA5EC69893A94E501F8FB3EC6321; Path=/tiles; Secure
  content-type: application/json
  content-length: 3759
  connection: close
  x-request-received: 1445716406438
  x-request-processing-time: 293
{ bu: 'tech',
  site: 'SDG',
  supervisor: 'xyz',
  title: 'CEO',
  worksite: 'SDG' }
```

**Comment by marcellodesales** [comment]
In addition to the above, I also want the support for the log level to map the response error code:

* ERROR: Err and HTTP Response Code is 500
* WARN: err or HTTP Response Code >= 400 
* INFO: Any other

```js
[2015-10-24T20:54:01.253Z]  WARN: sp-http-client/JSON-HTTP-CLIENT/59230 on ubuntu (/home/mdesales/dev/github-intuit/servicesplatform-nodejs/sp-http-client/lib/auditor/index.js:49 in audit):  (appVersion=0.1.0, remoteAddress=10.137.8.28, remotePort=443, req.timers={}, req.port=443)
  GET /people/wrong/url HTTP/1.1
  accept: application/json;application/xml
  authorization: IAM a=333;b=4444
  user-agent: sp-http-client/1.0.0 (x64-linux; v8/3.14.5.9; OpenSSL/1.0.1p) node/0.10.40
  accept-version: *
  date: Sat, 24 Oct 2015 19:53:26 GMT
  host: people.company.com:443
  --
  HTTP/1.1 404 Not Found
  date: Sat, 24 Oct 2015 20:54:01 GMT
  server: Apache/2.2.15 (Red Hat)
  content-length: 321
  connection: close
  content-type: text/html; charset=iso-8859-1
  x-request-received: 1445720040910
  x-request-processing-time: 338
  --
  NotFoundError
      at ClientRequest.onResponse (/home/mdesales/dev/github/restify/clients/lib/HttpClient.js:185:26)
      at ClientRequest.g (events.js:180:16)
      at ClientRequest.emit (events.js:95:17)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
      at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
      at CleartextStream.socketOnData [as ondata] (http.js:1584:20)
      at CleartextStream.read [as _read] (tls.js:514:12)
      at CleartextStream.Readable.read (_stream_readable.js:341:10)
      at EncryptedStream.write [as _write] (tls.js:369:25)
      at doWrite (_stream_writable.js:226:10)
      at writeOrBuffer (_stream_writable.js:216:5)
      at EncryptedStream.Writable.write (_stream_writable.js:183:11)
      at write (_stream_readable.js:602:24)
      at flow (_stream_readable.js:611:7)
      at Socket.pipeOnReadable (_stream_readable.js:643:5)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```
